name: Reusable Grader (xv6)

on:
  workflow_call: {}  # Allow external repositories to call

jobs:
  grade:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: read    # Read the code of the caller repository
      actions: read
      checks: write

    steps:
      # ① Checkout student repository code (automatically the caller repository)
      - name: Checkout student repo
        uses: actions/checkout@v4
        with:
          path: student

      # ② Checkout teacher grader (current repository)
      - name: Checkout grader repo
        uses: actions/checkout@v4
        with:
          path: grader_repo
          repository: ${{ github.repository }}  # This repository
          ref: main

      # ③ Install toolchain (xv6-riscv; x86 changes package name)
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            qemu-system-x86 \
            gcc \
            make \
            python3 python3-pip
          pip3 install --upgrade pexpect PyYAML

      # ④ Compile student code
      - name: Build xv6
        working-directory: student
        run: |
          make clean || true
          make -j"$(nproc)"

      # ⑤ Run grading (invoke scripts and rules from the teacher repository)
      - name: Run grader
        run: |
          mkdir -p student/grade-report
          python3 "${{ github.workspace }}/grade_proj1.py" --timeout 120
        working-directory: student

        
      # ⑥ Upload logs
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grade-report
          path: student/grade-report/*
